### ISSUE TITLE
Submission to bioconductor

### ISSUE THREAD

**Issue by svalvaro** [svalvaro/drawCell#1]
Hi @GregYannes,

I thought it would be a good idea to submit it to [Bioconductor](https://bioconductor.org/), I just added you as an author (you can add your email if you want) and during the following days, I'll add some documentation, vignettes and tests. 

Feel free to add more functions if you desire so!

Cheers,

Alvaro

**Comment by GregYannes** [comment]
Thanks Alvaro, I really appreciate it!

Life is still fairly crazy at the moment, so I doubt I can contribute any
functionality at present, but I have added my email: ***@***.***
Here's to the success of drawCell!

Best Regards — Greg

**Comment by svalvaro** [comment]
Thanks Greg! 
To the success of drawCell,
Best!

**Comment by GregYannes** [comment]
Hey Alvaro!  Just wanted to draw your attention to my pull request
<https://github.com/svalvaro/drawCell/pull/2>; I modified my branch to
include my email address, but only you can merge it.

Thanks! -- Greg

**Comment by svalvaro** [comment]
Hey @GregYannes, Merged! Thanks!
